### ISSUE TITLE
This is the absolute best - but could you make one change?

### ISSUE THREAD

**Issue by Zacharybinx34** [Aviana/ShadowedUnitFrames#11]
I love this addon, But I'm wondering if you could add an option for me?

On the Target frame, I would like to be able to use Class icons for PVP players and the 3D Portrait for PVE mobs. Is this possible?

Thank you!

**Comment by Zacharybinx34** [comment]
Also, the 2D Portrait model is too zoomed in. Any chance you could fix that? I'd rather use the 2D over the 3D if possible.

**Comment by Aviana** [comment]
The 2D has to be zoomed in because the original picture is round to fit the default frame.
Also i don't do feature requests. This is a backport so the addon will stay in its original format.

**Comment by Zacharybinx34** [comment]
Gotcha. Any way to freeze the 3d one then so it doesn't move?

**Comment by Aviana** [comment]
No.
