### ISSUE TITLE
Unit Frames disappear when reloading in combat.

### ISSUE THREAD

**Issue by Anteara** [Aviana/ShadowedUnitFrames#14]
Hi @Aviana , I'm currently working on a nameplate addon, which means I need to /reload in combat all the time. I initially thought it was my addon causing this issue, but I disabled all addons except for Shadowed Unit Frames, to see if that was true.

It's Shadowed Unit Frames causing this issue, you can recreate this issue by:

1) Log in
2) Disable all addons except SUF
3) Get in combat
4) type /console reloadui

Notice that the unit frames are now missing.

Screenshots:

http://i.imgur.com/j9PlOhi.jpg (Before Reload)
http://i.imgur.com/sk0v2iH.jpg (After Reload)

Thanks! I love SUF btw. I love Luna Unit Frames too :)

**Comment by Aviana** [comment]
Does that work with Pitbull Unitframes? Because the interface doesn't let you create button frames during combat. Maybe you can create them before everything is loaded. I will test it.

**Comment by Anteara** [comment]
Yep it works:

Before Reload: http://i.imgur.com/QMKKxDh.jpg
After Reload: http://i.imgur.com/m2MbWph.jpg

Frames are still visible!

**Comment by Aviana** [comment]
Fixed.

**Comment by Anteara** [comment]
Great. A one liner. Those are always the best fixes.
`or not ShadowUF.Initialized`

Do you have Discord? I've set up a server here for legacy addon developers:  https://discord.gg/KjYBVkY
