### ISSUE TITLE
Can't display target  hp value

### ISSUE THREAD

**Issue by yihu0259** [Aviana/ShadowedUnitFrames#15]
All good test with this addon so far and thanks for your contribution. 

Just have an issue that can't display specific hp value on target, only shown in percentage. I changed in many types, like short, absolute, smart and such things but it did not work. It only works fine when be in a team and the target is your teammate that can show this specific hp value.  May you have a check and fix it please? Thanks

**Comment by Aviana** [comment]
MobHealth3 support has been added (https://www.wowace.com/projects/project-14402)
