### ISSUE TITLE
Target current/max HP is (unless you target yourself) always in percent and not in absolute values.

### ISSUE THREAD

**Issue by kalayoutube** [Aviana/ShadowedUnitFrames#19]
See screenshot.
![w](https://cloud.githubusercontent.com/assets/29150343/26737769/d641f85c-47cb-11e7-9ade-173c6a4db329.png)

**Comment by Aviana** [comment]
The server doesn't show hp values to the client (blizzlike for TBC). Support for MobHealth has already been added.
