### ISSUE TITLE
Debuff Aura Timer not existing

### ISSUE THREAD

**Issue by Tr1n1ty1** [Aviana/ShadowedUnitFrames#24]
Debuffs put on the player don't show a time/timer/grey clock
It works for Buffs and debuffs on enemys but not debuffs on self, the blizzard UI does this so it shoud be working in this addon aswell

**Comment by Aviana** [comment]
Yes it doesn't work on WarGate. Because its shit.

Proper scripted server:
![auras](https://user-images.githubusercontent.com/425023/28973769-8144841a-7934-11e7-82aa-7c43b36e02c3.png)
