### ISSUE TITLE
Rclick to RaidFrame

### ISSUE THREAD

**Issue by Monteo** [Aviana/ShadowedUnitFrames#25]
![image](https://user-images.githubusercontent.com/24656088/28418090-b0699246-6d84-11e7-91a0-6bf113d12ef0.png)

**Comment by Aviana** [comment]
I don't control this code. SUF calls blizzard code and the blizzard code fails (poorly scripted server). They probably didn't notice it while scripting because the default ui doesn't have right click menus on raid frames.

**Comment by Monteo** [comment]
disable rclick in SUF
