### ISSUE TITLE
Party-pets - classes without a pet show white bars with "Unknown" name

### ISSUE THREAD

**Issue by switchpants** [Aviana/ShadowedUnitFrames#27]
If I enable the party-pet frames, SUF shows a white bar with name "Unknown" for classes that do not have a pet.  Classes with pets are displaying properly.

If (while in group) I disable and re-enable party-pet frames in SUF, the white bars disappear.  So this is a bit of a work-around to get things to display correctly.

Raid-pet frames work fine.

This could be a server-side issue perhaps...  Can let me know which TBC server you have tried -- so I can test to see if the same thing happens there.

**Comment by Aviana** [comment]
Been testing on Smolderforge. WarGate seems really buggy.

**Comment by Simon3** [comment]
Issue and work-around confirmed on Warmane Outland
