### ISSUE TITLE
Lifebloom Aura Timer

### ISSUE THREAD

**Issue by Ironjudgment** [Aviana/ShadowedUnitFrames#28]
I've notcied an issue with the stacked Lifebloom buff on all frames. Once you stack Lifebloom 3 times (timer still works) and cast another Lifebloom without the previous 3 stack to bloom the timer does not reset and goes completely gray.

**Comment by Aviana** [comment]
Not a bug. Its the Server.

**Comment by Ironjudgment** [comment]
Grid and xpearl timers are working correctly tho.
