### ISSUE TITLE
Incorrect Poisons display on rogue, freezing when adding certain auras

### ISSUE THREAD

**Issue by Red86** [Aviana/ShadowedUnitFrames#29]
Hello,
while using the same poisons on both main and offhand weapons on a rogue, the temporary weapon enchant aura icons if activated in the auras tab of the player section for the options menu will often bug out by displaying either only one icon or, duplicating the icon of anoter buff aura that is present on the player at the moment. (For example I had two stealth icons) The issue is always fixed by reloading the UI and happens only when you're using the same poison on both weapons.

Aura filters seem bugged too. When I tried to add certain debuffs auras to a whitelist for the target, inputting certain names like "Mangle (Bear) would cause the screen to freeze and become unresponsive. Not sure if it's a server issue (Playing on Twinstar Ares) or is something with the frames

**Comment by Aviana** [comment]
Could not reproduce the freezing.
