### ISSUE TITLE
Aura filters Arena 2.4.3

### ISSUE THREAD

**Issue by bellner** [Aviana/ShadowedUnitFrames#36]
First of all love the addon but I feel its missing some keyfeatures that the 3.3.5 version have.

So on the 3.3.5 version there is an option in Auras so only display your own buffs and thats not in the 2..4.3v. Thats fine I manually added every buff to the blacklist filter and at first it worked like a charm but
when I enter any arena all the blacklist filters stop working and there doesn't seem to be and option to apply black/whitelist auras to Arenas, when I leave the arena all aura filters work again.

in arena: https://i.imgur.com/g1ijPHT.jpg
outside arena (notice that my target frame shows the buffs but party frames does not): https://i.imgur.com/Dp6Bh6B.jpg

**Comment by MartMlr** [comment]
Hey bellner, 
I had this issue before, the fix is rly simple though.

Just change `local zoneList = {"none", "pvp", "party", "raid"}` to `local zoneList = {"none", "pvp", "party", "raid", "arena"}` in the ShadowedUF_Options/config.lua file.

**Comment by bellner** [comment]
I tried it and it works perfectly now! thanks for quick reply
