### ISSUE TITLE
[Feature Request] Breath and Fatigue indicators

### ISSUE THREAD

**Issue by minetrinitite** [Aviana/ShadowedUnitFrames#38]
Right now indicators are displayed with all other debuffs on player.

It would be better create an option to keep the default frames for Breath and Fatigue.

Originally they are not displayed with all other debuffs on player, but emphasized with individual bars in the center of the screen. So, right now it is hard to keep focus on such vital parameters during the battle.
I even wonder if it is a side effect of the addon architecture and debuff handling.

**Comment by Aviana** [comment]
ShadowedUnitFrames does not interact with the default breath and fatigue bars in any way.
