### ISSUE TITLE
MobInfo support

### ISSUE THREAD

**Issue by AndHabb** [Aviana/ShadowedUnitFrames#39]
ShadowedUF doesn't show the health value specified by MobInfo2. The health value is shown in the MobInfo tooltip and X-Perl, but with this addon it only shows that all mobs have 100 HP.

**Comment by Aviana** [comment]
#12 https://github.com/Aviana/ShadowedUnitFrames/commit/f5d2e8b64bce4c1761470c5131eaf05e991e633e

https://www.wowace.com/projects/project-14402/files/135890

**Comment by AndHabb** [comment]
If I use Mobhealth, sometimes the level and health value will not update after I select a new target. So no matter which player or NPC I target they all show the same level and max health.
