### ISSUE TITLE
Target values not updating after selecting new target

### ISSUE THREAD

**Issue by AndHabb** [Aviana/ShadowedUnitFrames#40]
Sometimes after I've selected a target, the level and max health value is not updated when I select a new target. If I click on for example a lvl 28 with 1050 health, then all players and NPCs I target afterwards will show as lvl 28 with 1050 health until I relog.

**Comment by AndHabb** [comment]
I'd like to add more to this issue. Sometimes buffs and debuffs stop updating for player, and disappear alltogether for target and party. On one occurence unlocking the frames would not turn the inactive frames visible without locking and unlocking them multiple times, and the whole addon was just a mess until relogging.
List of addons:
Mobhealth4
Ace, Ace2, Ace3
Atlasloot
AtlasQuest
Bagnon
Bartender4
Mobinfo2
MoveAnything
OmniCC
Quartz
Questhelper
Recount
SellJunk
Vendorvalues

**Comment by AndHabb** [comment]
After playing for a while, buffs and debuffs will stop showing for target and party until relog. Attempting to disable and re-enable target buffs in the options menu will for some reason just enable and disable the cast bar for target.
If this happens and I unlock the frames, the frames will not be lockable again until relog. It seems every time I play for a while the addon just becomes corrupt until I go to character select screen and back in.

**Comment by Aviana** [comment]
I am using this addon on a daily basis and have never seen issues like this. Please check if these issues happen with only SUF enabled.

**Comment by sonyahz** [comment]
I'm also having these issues. Occasionally upon relogging in a raid or party, unlocking frames, or reloading, my frames will become extremely buggy. 

Just as AndHabb said, when you target a player or mob and then try to target something different, the target frame and the target of target frame will display the incorrect name, class, values and percentages of health/mana and so on. The only informaton that's seemingly correct is the 3D model and the color of the health bar indicating class.

Additionally /reloading and trying to lock and unlock the frames doesn't fix the issue. Again like AndHabb described, unlocking the frames makes the entire addon permanently glitch out. All frames look like a mess and do not go away when you lock the frames again.

Addons: 
AtlasLoot
Cartographer
Chatter
DBM
MobHealth
NeedToKnow
Omen
OmniCC
Pallypower
Quartz
Questhelper
Recount
Vendervalues

**Comment by Aviana** [comment]
This error will happen when you are encountering a lua error. Enable their display and post them here. Be sure to to download the most recent version first.
