### ISSUE TITLE
MobHealth3

### ISSUE THREAD

**Issue by illumis2** [Aviana/ShadowedUnitFrames#44]
Using the version of Mobhealth3 you have previously linked and cannot get mob health to show after updating to newest version.

**Comment by Aviana** [comment]
![WoWScrnShot_042219_112014](https://user-images.githubusercontent.com/425023/56493921-f3fec700-64f0-11e9-9fc9-01c274fa9dc0.jpg)

Looks fine to me

**Comment by illumis2** [comment]
Hey, after you posted I thought i would do some more testing. Using MobHealth3 I can get the health to show for xperl and the blizzard default frames but am still not seeing values in SUF. The issue started immediately after updating versions posted here a month ago. Not sure if it is related but i am seeing LUA errors every time i gain/lose an aura/buff. Is there any thing that would be useful for me to post? 
![SUFoption](https://user-images.githubusercontent.com/47857839/56503214-b60f9c00-650c-11e9-9228-c6111e1b5af5.png)

**Comment by Aviana** [comment]
Lua errors are never a good thing. They could break the functionality of the corresponding frame. You could start by posting those.

**Comment by illumis2** [comment]
Here is the LUA errors, though these errors only seem to happen on my warlock but both my warlock and druid cannot see enemy health. The errors appear every time i receive or lose a buff
![luaerrorsuf](https://user-images.githubusercontent.com/47857839/56540450-ade14c00-6560-11e9-9f8e-66f91b74cffb.png)

**Comment by illumis2** [comment]
Thought i'd update after more testing. Tried reinstalling after deleting all saved variables but the issue didn't improve. After I uninstalled and have installed version 1.7 which gives me mob health values just fine.

**Comment by Aviana** [comment]
I finally figured out what happened. The code for MobHealth3 somehow got deleted in one of the commits but i continued to see the health of mobs because i was using LibMobHealth-4.0.
