### ISSUE TITLE
Lifebloom refresh a bit buggy

### ISSUE THREAD

**Issue by Notmelody** [Aviana/ShadowedUnitFrames#8]
https://streamable.com/qowb

Sometimes refreshing a stack just before it finishes in this case gets "stuck" and will not refresh untill the lifebloom aura is removed.

Is there any way you could fix this issue? im torn to use it but with this issue as a resto druid its not making me use it :<

**Comment by Aviana** [comment]
Looks like serverlag. No way to make that reliable. The mod is responding to events it gets from the server.
